/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContenidosRouteImport } from './routes/contenidos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as GenerarRouteImport } from './routes/generar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenidosRoute = ContenidosRouteImport.update({
  id: '/contenidos',
  path: '/contenidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerarRoute = GenerarRouteImport.update({
  id: '/generar',
  path: '/generar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contenidos': typeof ContenidosRoute
  '/cursos': typeof CursosRoute
  '/generar': typeof GenerarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contenidos': typeof ContenidosRoute
  '/cursos': typeof CursosRoute
  '/generar': typeof GenerarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contenidos': typeof ContenidosRoute
  '/cursos': typeof CursosRoute
  '/generar': typeof GenerarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contenidos' | '/cursos' | '/generar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contenidos' | '/cursos' | '/generar'
  id: '__root__' | '/' | '/contenidos' | '/cursos' | '/generar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContenidosRoute: typeof ContenidosRoute
  CursosRoute: typeof CursosRoute
  GenerarRoute: typeof GenerarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenidos': {
      id: '/contenidos'
      path: '/contenidos'
      fullPath: '/contenidos'
      preLoaderRoute: typeof ContenidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generar': {
      id: '/generar'
      path: '/generar'
      fullPath: '/generar'
      preLoaderRoute: typeof GenerarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContenidosRoute: ContenidosRoute,
  CursosRoute: CursosRoute,
  GenerarRoute: GenerarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
